### ISSUE TITLE
Colour variable re-write to allow generic NHS use

### ISSUE THREAD

**Issue by jdbrew** [NHSLeadership/nightingale#102]
re write `_settings.definitions.scss`and `_settings.colors.scss` to cover whole NHS colour palate and allow for the definition of organisational accent secondary colours from the palate.

**Comment by cehwitham** [comment]
@jdbrew was this completed?

**Comment by jdbrew** [comment]
I submitted `_settings.definitions.scss` to https://github.com/NHSLeadership/nightingale/commit/d7a2550d678d82a276ec3b8afcb06ed95a314ea5

**Comment by cehwitham** [comment]
@csswizardry I believe this is ready for you to implement the accent colours as discussed with @jdbrew

**Comment by penpadstudio** [comment]
Has this been completed @jdbrew ?

**Comment by csswizardry** [comment]
I’d like to elaborate on this a little more if we can. @jdbrew’s ‘`// to-do: does this work?`’ implies this is a little more complex than has been let on 😉

**Comment by cehwitham** [comment]
@jdbrew give me a call to discuss this at some point.

**Comment by csswizardry** [comment]
Closing this due to lack of appetite.
