### ISSUE TITLE
Request: Hero Component

### ISSUE THREAD

**Issue by chriscoffee** [NHSLeadership/nightingale#103]
Not sure this has been mentioned yet but think we need to create hero component. 

- caption
- link
- modifiers: cover, fit

I don't mind sorting out some of it.

Not sure if priority @Pro-Paul can highlight this.

**Comment by cehwitham** [comment]
@Pro-Paul do we have designs for this?

**Comment by penpadstudio** [comment]
We have media elements that will act as heroes if needed.
![screen shot 2017-09-08 at 09 54 52](https://user-images.githubusercontent.com/23170050/30203976-cccfb96a-947b-11e7-88ad-ae3f899d2866.png)
