### ISSUE TITLE
Closing burger menu causes menu to disappear

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#106]
The burger menu that appears when the browser window is below a certain width can be clicked to toggle the mobile menu on and off. But if it's toggled off, that setting is retained when the browser width is enlarged, leaving the menu hidden.
![screen shot 2017-07-18 at 15 13 23](https://user-images.githubusercontent.com/1991226/28321816-257bcf00-6bcc-11e7-80cb-4cf1b69923c3.png)

**Comment by ishanivardhan** [comment]
Steps to replicate this:

1. Either resize your browser window or change to Mobile viewport
2. Click on hamburger menu option; You should now see a cross icon image.
3. DO NOT click on Cross icon image; Instead resize your window back to normal/desktop size.

Actual O/P: The navigation/menu items disappear
Expected O/P: The navigation/menu items should go back to their normal shape & visibility

cc: @csswizardry

**Comment by Android63** [comment]
This has been fixed, probably in https://github.com/NHSLeadership/nightingale/issues/108, so I'm closing this issue.
