### ISSUE TITLE
Cookie ribbon close button

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#112]
Should the closing the cookie ribbon when the close button is clicked be built into Nightingale? I'm thinking it could be js to hide the element.
![screen shot 2017-07-19 at 14 45 20](https://user-images.githubusercontent.com/1991226/28369950-f2271220-6c90-11e7-9153-9227d5ebe885.png)

**Comment by Android63** [comment]
Also, once a particular user has closed it, I guess it should stay closed for them which, ironically, might need a cookie...

**Comment by Android63** [comment]
Also, If the purpose is to cover ourselves legally, shouldn't the close icon say something like "I Accept"?

**Comment by csswizardry** [comment]
I’ve added a simple bit of JS to make the ribbons dismissable (c41f9da), but the actual setting of cookies etc. falls out of Nightingale’s remit.
