### ISSUE TITLE
Footer markup incomplete

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale#116]
@csswizardry - As per @Pro-Paul 's design the mark-up for links with "pipe" separator and copyright info below the divider is missing in the Footer of Nightingale.

Please see the screenshot from Design here
<img width="1137" alt="screen shot 2017-07-28 at 12 18 59" src="https://user-images.githubusercontent.com/25176815/28715256-f820f682-738e-11e7-9cab-909c9bb14915.png">
I think the mark-up bit may not be complicated, just need to put the font & pipe separator styling for links & copyright text as per the design. 

An example of "pipe" separator styling that I tried is listed below but I'll leave this to the pro to decide the best way of doing it.
`li:not(:last-child) {
    border-right: 1px solid grey;
    padding-right: 20px;
    margin-right: 20px;
}
`

Would you be able to pick this up on priority when you work next?

**Comment by penpadstudio** [comment]
Padding and margin should be 10px each
