### ISSUE TITLE
Moodle Header

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale#117]
Since Moodle Header & mark-up is slightly different than our current Nightingale design, this issue is to track any separate design changes that needs doing to accommodate Moodle layout.

<img width="1277" alt="screen shot 2017-08-01 at 12 13 23" src="https://user-images.githubusercontent.com/25176815/28824079-69dfa7b0-76b8-11e7-8af6-5c3e80dcb3a4.png">

This is how Moodle header could look like based on initial discussion with @Pro-Paul but there is room for minute details/technicalities that will address in this issue.

**Comment by ishanivardhan** [comment]
@Pro-Paul - We need a mock-up of how "Notifications" sub-nav should look like in Nightingale structure. I had sent you screen-shots of what Moodle Notifications pop-up look like with or without Notifications. It would be great if you can attach what sub-nav should look like when clicked to fit-in those screen shots.

**Comment by ishanivardhan** [comment]
@Pro-Paul - We may also need a mock up of what "Profile" sub-nav should look like in Nightingale structure. 
Current Moodle User Profile dropdown look like the screenshot below when clicked.
<img width="217" alt="screen shot 2017-08-01 at 12 50 24" src="https://user-images.githubusercontent.com/25176815/28823990-07707dc0-76b8-11e7-90c0-13479f36ea0a.png">

Since we don't have the icons used in these drop-downs, nor the mock-up of what Sub-nav should look like when it has no action button and just sub-items such as the above screenshot, it would be great if you build a mock-up to incorporate these.

**Comment by penpadstudio** [comment]
@ishanivardhan I have uploaded some design files: https://share.goabstract.com/ae33f33d-dbf7-4c11-ad35-8b1bf1abc93d

**Comment by ishanivardhan** [comment]
@Pro-Paul - This requires me to be granted access to NHSLA even though I'm logged onto Abstract? Would it be easier if you just let me know briefly as to what designs you have uploaded and what file names I need to look out for?

**Comment by ishanivardhan** [comment]
@Pro-Paul - The latest designs attached is different from current Nightingale Header. I assume we need to get this built from @csswizardry first for me to incorporate in Moodle?

![screen shot 2017-08-04 at 10 53 43](https://user-images.githubusercontent.com/25176815/28964102-5c996b16-7903-11e7-91e8-ca5ac926302f.png)

**Comment by cehwitham** [comment]
So I think Profile button is in v1.0.0. The notification highlight isn't necessarily a priority.

**Comment by ishanivardhan** [comment]
@cehwitham - The designs have changed since then based on our discussion of not involving Notifications & Messages. Pls take a look at below:

![screen shot 2017-08-17 at 10 13 12](https://user-images.githubusercontent.com/25176815/29405055-bb608b94-8334-11e7-8aed-dc3b46464553.png)

This still needs some tweaks but the basic idea is there. 

- Ignore the red dot; We dont need it any more.
- Students see "Contact" in Header where as Site Admins would see "Site Admin" link
- @Pro-Paul needs to stick in Log Out button/link somewhere too as that's not there in this design. I suggested a button next to Profile button or any other thoughts @cehwitham ?

We can discuss on top of this design now, if required. Abstract is the place for changes from @Pro-Paul for this design!

**Comment by cehwitham** [comment]
> Students see "Contact" in Header where as Site Admins would see "Site Admin" link

This seems like Moodle implementation, not styling?

> @Pro-Paul needs to stick in Log Out button/link somewhere too as that's not there in this design. I suggested a button next to Profile button or any other thoughts @cehwitham ?

@Pro-Paul's shout on where the log out button goes, not mine.

**Comment by penpadstudio** [comment]
I want to point out that in order to compromise on capabilities I removed the previous profile dropdown options and replaced with the single profile button in mind that the user is directed to the profile page which would display all settings etc...including a logout action. 

Anyway I have created the option to have a profile and logout button on the nav as requested due to capabilities. 

![screen shot 2017-08-17 at 10 56 20](https://user-images.githubusercontent.com/23170050/29407007-baaf9b9e-833a-11e7-9e02-a40d7c69a764.png)

**Comment by penpadstudio** [comment]
I know this looks strange but we already set the primary to be blue and secondary to be white. Maybe we can switch in this context. needs a little more thought, unless we can switch the logout to the profile page?

**Comment by penpadstudio** [comment]
Maybe we just scrap the whole blue banner, seems its quicker and easier route.

**Comment by penpadstudio** [comment]
Thoughts?
![screen shot 2017-08-17 at 11 12 30](https://user-images.githubusercontent.com/23170050/29407656-ff428594-833c-11e7-84d1-04075c0e32d5.png)

**Comment by ishanivardhan** [comment]
@Pro-Paul - That looks neat to me! And the buttons contrast well!

**Comment by cehwitham** [comment]
@Pro-Paul what was the initial design decision for the blue banner? Seems we don't want to just throw it out because we have a question about a button? Adding a white on white button seems similar to adding a blue on blue button? Do we need to review having two buttons in the header instead of trying to sort out styles for them?

**Comment by penpadstudio** [comment]
Well the initial reason was to create a separate UX from external platform to internal platform. I believe the white on white works better for now plus its built already. I am only suggesting revisiting the blue header in another release, my mind set is more on hitting this deadline now. @ishanivardhan recommends that sign out is on nav as signet being on profile page is not in Moodle capabilities and I am happy to accommodate this best way I see fit by my suggestions. we can't burn the candle at both ends and expect a good product. so this is the compromise.

**Comment by ishanivardhan** [comment]
@Pro-Paul , @cehwitham - Thoughts on final Header design so accordingly we can have @csswizardry build anything that isn't there already?

**Comment by cehwitham** [comment]
Happy for @Pro-Paul to update the designs as he sees fit and communicate any requirements or changes to @csswizardry

**Comment by penpadstudio** [comment]
I am taking the executive decision to leave the blue banner out of the design build for version 1 release. Please now revert back to white banner until further update on the issue.

**Comment by ishanivardhan** [comment]
Few components of header might need some work based on Moodle designs:

1. The c-btn--primary is purple, needs to be blue

2. Adding buttons in header makes it go a bit mis-aligned
![screen shot 2017-08-18 at 16 45 06](https://user-images.githubusercontent.com/25176815/29466516-072d1622-8435-11e7-9ab6-a912ed2ee786.png)

After reducing the padding for c-btn--primary & aligning the list item link for c-nav-primary__item it did look fine but not quite in line with logo
![screen shot 2017-08-18 at 16 49 46](https://user-images.githubusercontent.com/25176815/29466782-1046c91e-8436-11e7-84e0-58f140f18c58.png)

3. Maybe we need the white button as it's in Moodle design to be created? The white as isn't giving the thick button effect.

@Pro-Paul , @cehwitham , @csswizardry

**Comment by penpadstudio** [comment]
> The c-btn--primary is purple, needs to be blue

Agreed we should update the colour value to NHS Blue for v.1 release. Also should make sure to swap the font colour to NHS blue as well on secondary.

>Adding buttons in header makes it go a bit mis-aligned

So in terms of alignment we need to organise it better for sure looking at @ishanivardhan screenshots.
Please see below:

![untitled_artwork](https://user-images.githubusercontent.com/23170050/29517884-088320a2-866f-11e7-9ce5-2da373612b6a.jpg)

>Maybe we need the white button as it's in Moodle design to be created? The white as isn't giving the thick button effect.

The styling you refer to has not been implemented yet as it was re-visited after build of first iteration of buttons. If we get all other assets for v1 done then I think we can re-visit the button styling build.

**Comment by csswizardry** [comment]
What does all this look like on smaller screens?

@Pro-Paul: As the design is completely fluid, we really need to stop thinking in terms of 632px, etc.

**Comment by ishanivardhan** [comment]
@csswizardry - Do you need a Mobile view of what Moodle Header currently looks like?

**Comment by penpadstudio** [comment]
@csswizardry Sorry the header above is for desktop tablet. then once the device screen is decreased past the width above then the menu system should default to the mobile menu icon to open up the menu:

### Lowest value:
![screen shot 2017-08-23 at 10 37 09](https://user-images.githubusercontent.com/23170050/29609404-056ceeee-87ef-11e7-9071-fa4da6705179.png)

### Middle value:
![screen shot 2017-08-23 at 10 38 09](https://user-images.githubusercontent.com/23170050/29609454-2d7b29f0-87ef-11e7-9944-5749c25a5b28.png)

### Highest value:
![screen shot 2017-08-23 at 10 38 43](https://user-images.githubusercontent.com/23170050/29609481-4072ee58-87ef-11e7-9570-f213926cc067.png)

**Comment by csswizardry** [comment]
I meant when it’s open… what should the buttons do?

**Comment by ishanivardhan** [comment]
@csswizardry - The buttons in above screen shot just act as links. They redirect you to a different page and aren't sub-navs in this case, if that helps!

**Comment by csswizardry** [comment]
@ishanivardhan: For the alignment issue, there’s a new button style coming in #137. The newly introduced `.c-btn--natural` class will make a button take up only as much space as it naturally needs. See 701274f for the code :)

**Comment by jdbrew** [comment]
Is this issue closed becuase of #137 @cehwitham @csswizardry ?

**Comment by ishanivardhan** [comment]
No @jdbrew , this issue is still very much open. The issue above is from my repository moodle-theme_nigthingale where the Header is partially complete & done.

**Comment by penpadstudio** [comment]
Hi @ishanivardhan  I am closing this issue a. because this should have originally been hosted on the Moodle nightingale repo not the Nightingale original repo as it seems to affect Moodle more, b. it seems quite old and dated and not defined to one issue. If you need to re-open please feel free to copy and of this and re-post on the Moodle Nightingale repo. Thanks.
