### ISSUE TITLE
When hints met `@extend`…

### ISSUE THREAD

**Issue by csswizardry** [NHSLeadership/nightingale#123]
@Android63 spotted an interesting issue that arises in certain scenarios in which we’re using out Hints module alongside out middleware:

![image](https://user-images.githubusercontent.com/751944/29215043-5ee8497a-7ea1-11e7-9a6e-9b93b7ae91fe.png)

The problem is that when we use `@extend` in our middleware layer, selectors imitating others can accidentally trigger Hint errors, giving false positives.

Currently, I think the only solution would be to rip out the offending Hints. A longer-term solution would be to double up potentially `@extend`able selectors with `%` silent selectors. Maybe.

**Comment by Android63** [comment]
Could this be solved with the !important tag @csswizardry?

**Comment by ishanivardhan** [comment]
@csswizardry - One more example of this when I was working on breadcrumbs in Moodle. I had to use @extend (middleware) to apply Nightingale styles as markup is buried deep within core files.

`ol.breadcrumb>li:first-child a {`
  `@extend .c-breadcrumb__link;`
  `@extend .c-sprite;`
  `@extend .c-sprite--home;`
`}`

And with the above, I get hints error 'You probably need a Modifier on this elements’s Block."

**Comment by csswizardry** [comment]
Set `$global-hints: false;` in  your project, just before you `@import` nightingale 👍

**Comment by ishanivardhan** [comment]
Yes @csswizardry I was suggested that by @Android63 but I thought maybe keeping hints ON would point out any discrepancies or missing class/modifiers which is really helpful. But I have the global hints switched OFF for now! 👍

**Comment by penpadstudio** [comment]
@csswizardry @Android63 @cehwitham Is this issue solved? Is this a priority for v.1 Nightingale?

**Comment by ishanivardhan** [comment]
Yes with the fix from @csswizardry dated 4th Sept 2017, it works fine for me.

**Comment by penpadstudio** [comment]
@ishanivardhan Are we happy to close this issue then?

**Comment by ishanivardhan** [comment]
Fine by me @Pro-Paul unless @Android63 or @cehwitham have something to add.
