### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#133]

**Comment by cehwitham** [comment]
@Pro-Paul is there a particular design for this?

**Comment by penpadstudio** [comment]
will just use hierarchy of headings and body copy and links. Example design layout is live in abstract: https://share.goabstract.com/e4d7c557-a67e-46e5-87b5-63666ee9e40d

**Comment by cehwitham** [comment]
@Android63 can you close this if you're happy with it please?
