### ISSUE TITLE
Placeholders not supported in IE8

### ISSUE THREAD

**Issue by chriscoffee** [NHSLeadership/nightingale#143]
This is pretty standard but need to decide how and even if we're going to sort this. I'm against going down the jQuery root as I'm sure others are.

**Comment by csswizardry** [comment]
I don’t think we need to worry about supporting this in IE8. The effort involved in fixing it would be an order of magnitude greater than the benefits we’d reap.

Plus, as a general UX rule, all form fields should be clearly understood if `placeholder` text is absent (e.g. whilst you’re actually filling the field in).

**Comment by chriscoffee** [comment]
That's fine. I'll now mark this as closed given Chris gave this the +1. It was more a question for Chris/Paul anyway.
