### ISSUE TITLE
Fix nav alignment

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#146]
Menu items are not aligned with any buttons in the main menu.
![screen shot 2017-08-25 at 12 06 19](https://user-images.githubusercontent.com/1991226/29711671-ef839b32-898d-11e7-86ca-75fceeaade21.png)

**Comment by chriscoffee** [comment]
Has this been taken from the examples of how to use the framework (index.html) or some work you are currently working on?

The framework has all the tools needed to align the menu list items with the button you've created or vice versa

However, if there is something stopping you from aligning said buttons that isn't currently in the framework then can you please write up this but report correctly.

Some examples of how to achieve this could be a snippet of the code you've written. What you're trying to achieve. Things you've tried. Where you feel the issue could be.

**Comment by Android63** [comment]
Harry addressed this in PR #151
