### ISSUE TITLE
Change font size for h5 and H6

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#148]
h5 and h6 should both be 14px

https://user-images.githubusercontent.com/23170050/29411427-aac0b4a4-834c-11e7-993d-3fc88f3d6c06.png

**Comment by penpadstudio** [comment]
Updated design file as H6 indicting 19px was a typo...it is now reverted to 14px.
See abstract: https://share.goabstract.com/670d7b44-41b5-4a03-a218-739891393d05

**Comment by penpadstudio** [comment]
Having looked at the develop branch H4,5,6 are all set to what appears to be 19px:
![screen shot 2017-09-04 at 11 57 01](https://user-images.githubusercontent.com/23170050/30023678-5cfc23a0-9168-11e7-81d8-ba291a7cf06b.png)
H5,6 need to be converted to 14px as per design file in abstract above.

**Comment by cehwitham** [comment]
@Android63 looking at @Pro-Paul's file above, H4, H5 and H6 are all the same size?

**Comment by Android63** [comment]
> looking at @Pro-Paul's file above, H4, H5 and H6 are all the same size?

Screenshot above is out of date. Here's the latest

https://share.goabstract.com/713deada-226f-44f5-b8f4-c035ef33f92a

**Comment by csswizardry** [comment]
Is this merged in now?

**Comment by Android63** [comment]
Yes
