### ISSUE TITLE
Floating buttons

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#152]
Creation of floating buttons for quick scroll up and down pages:
![screen shot 2017-09-08 at 10 11 02](https://user-images.githubusercontent.com/23170050/30204642-0c815bac-947e-11e7-9b24-71434d84fa37.png)

@cehwitham suggestions on assignees?

**Comment by cehwitham** [comment]
Where should these sit on the page @Pro-Paul ? Do you have a design with them in situ?

**Comment by penpadstudio** [comment]
They sit at the bottom of device screen and raised on z- axis:
![screen shot 2017-09-08 at 12 53 42](https://user-images.githubusercontent.com/23170050/30210511-d78485b6-9494-11e7-9e7e-7e7a8b196bfc.png)

**Comment by cehwitham** [comment]
Is this only on mobile? What about scroll down?

**Comment by penpadstudio** [comment]
Not just on mobile, desktop as well i.e. scroll down buttons will be used to indicate to users when not un-abundantly clear more content below the fold of the page.

**Comment by cehwitham** [comment]
Do you have an image of how this will look @Pro-Paul ?

**Comment by penpadstudio** [comment]
@cehwitham for the time being we might leave this off v1 and add in after as it doesn't seem to be built in anyway and we have still to add in the pattern guidance on it I believe. Will close the issue for now and re-open when needed.
