### ISSUE TITLE
Bullets and numbers

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#158]
<img width="319" alt="screen shot 2017-09-08 at 11 15 20" src="https://user-images.githubusercontent.com/23170050/30207317-0a76a4bc-9487-11e7-8da7-366429362a43.png">
@cehwitham set priority please.

**Comment by csswizardry** [comment]
Coming all the way live, from Belarus:

![image](https://user-images.githubusercontent.com/751944/30265987-90309cf0-96e6-11e7-8289-c914948bac31.png)
