### ISSUE TITLE
Search Input with button

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale#169]
As per @Pro-Paul 's designs for "Forum Search in Moodle", I think we would need Search input with magnifying glass button inside it made in Nightingale 

![screen shot 2017-09-19 at 16 31 07](https://user-images.githubusercontent.com/25176815/30600781-4603479a-9d58-11e7-9b6b-371b49df7e25.png)

Tried quick fix by putting the magnifying glass sprite image on input text box for now but doesn't have the same effect so having this made in Nightingale will be helpful.

cc: @cehwitham Pls assign the priority as if not super high, this will be required for Moodle v1 at some point

**Comment by Android63** [comment]
@ishanivardhan I think we may be able to close this one as I've implemented the search bar in issue https://github.com/NHSLeadership/nightingale/issues/86

**Comment by Android63** [comment]
Closing this as it's in Nightingale.

For reference use:
```
<button class="c-search__btn">
      <span class="c-sprite  c-sprite--magnifying-glass-rev">Search</span>
</button>
```
