### ISSUE TITLE
Moodle File picker

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale#171]
As per our discussions earlier, Moodle forms have an Attachment area & relevant file picker that looks like below:

![screen shot 2017-09-25 at 17 09 52](https://user-images.githubusercontent.com/25176815/30818788-75147372-a214-11e7-96dc-a5c888a1f97a.png)
 
![screen shot 2017-09-25 at 17 10 09](https://user-images.githubusercontent.com/25176815/30818787-7511a19c-a214-11e7-9a09-87c04afc3a4e.png)

For now using Moodle's default styles for Attachment/File picker area & it's respective file picker modal dialog / popup.

But we need to create & build design for this in future version.

cc: @cehwitham Pls assign priority for this as appropriate. Thanks!

**Comment by penpadstudio** [comment]
Closed due to being in the wrong repo. Please move to Moodle repo if needed @ishanivardhan
