### ISSUE TITLE
Additional markup needed to accomplish Styling?

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale#174]
Hi @csswizardry ,

This is more of a question than an issue which you'd be the best person to answer. 

Few of the styling pieces in Nightingale are dependent on additional HTML mark-up and it's a bit of a puzzler to accomplish the same styling in a framework such as Moodle where the markup cant be easily changed (or added) as they sit in core files (not customisable). 

I’ll explain that with an example. So for checkbox - the markup is:

```
<label class="c-form-checkbox">
      <input type="checkbox" class="c-form-checkbox__input" checked="">
      <span class="c-form-checkbox__faux"></span>
      Phone
</label>
```

To get the nice little “green” checkbox effect when you click on it, you have to have a `span` after your `input checkbox` with those exact CSS classes. 

I have the `label` & `checkbox` style applied but not the ability to add a `span` tag and hence the checkbox squares don't show up for me at all.

Similar example for Select drop-downs:

```
<div class="c-form-dropdown">
                <select class="c-form-dropdown__select  c-form-input" id="title">
                  <option>Miss.</option>
                  <option>Mr.</option>
                  <option>Mrs.</option>
                  <option>Ms.</option>
                </select>
              </div>
```

If we don't have a `div` or really any parent element wrapping the `select` element, then it gets difficult to add `c-form-dropdown` class which actually has the downward arrow to make it look like a dropdown. So, currently my drop-downs just look like long text boxes.

Is there a way achieve all this without changing or adding the extra markup? Or the elements having all the styling it needs on them directly?

I'm sure there would be a good reason for you to add the CSS classes on additional mark-up to achieve the effects we need but can you suggest any tips to accomplish it without having to add/change a lot of markup?

Thanks in advance!

cc: @cehwitham , @Android63

**Comment by Android63** [comment]
I think this is an important point. Whilst I have select elements working in Gravity Forms, for example (because I've written filters to change the markup), this doesn't cover the eventuality of someone using a different forms plugin with different markup. If the select element was targeted directly, without adding any extra markup, then *all* select elements would be styled correctly without the need to write filters or change markup specifically for each plugin/form.

**Comment by Android63** [comment]
This is an interesting article on styling <select> elements without needing additional wrapper markup: [http://blog.room34.com/archives/5465](http://blog.room34.com/archives/5465)

Also this: [https://jsbin.com/diqene/edit?html,css,output](https://jsbin.com/diqene/edit?html,css,output)

**Comment by penpadstudio** [comment]
@ishanivardhan was this resolved? Should we move this to Moodle as its more of a question designed for the styling in Moodle...?

**Comment by ishanivardhan** [comment]
Sure @Pro-Paul ! Thanks!

**Comment by penpadstudio** [comment]
@ishanivardhan closed issue, feel free to move to Moodle repo. thanks.
