### ISSUE TITLE
Link sample with new-window-rev icon

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale#175]
After reviewing Moodle theme development, it was found that we need a sample for what the link would look like with new-window-rev icon and the optimum spacing between the two.

@cehwitham - Could you please assign this to the right person with priority?
cc: @Pro-Paul , @csswizardry 

PS: Apologies, if this is already done & would be great if pointed towards the code to view this!

**Comment by Android63** [comment]
I'm wondering if we should be using this at all. See https://github.com/NHSLeadership/nightingale/issues/176

**Comment by penpadstudio** [comment]
Closed due to being Moodle specific, please feel free to pick up again in Moodle repo @ishanivardhan
