### ISSUE TITLE
Use correct logo size in header

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#178]
At the moment, the logo used in the sample page is 204 by 62 pixels, which is smaller than it should be:
![screen shot 2017-12-08 at 10 58 53](https://user-images.githubusercontent.com/1991226/33763043-d2b1cddc-dc06-11e7-9683-c0d850f0b422.png)
We should replace this with one that is 245 by 72.

**Comment by cehwitham** [comment]
@Android63 what are we using to judge this as "wrong"?

**Comment by Android63** [comment]
https://app.goabstract.com/projects/fdbbd970-72f5-11e7-833e-970465c5fe77/branches/master/commits/a66e7f1633ba0b26423bd648660382738e321567/files/23927D9B-BCE6-47EC-90DA-D555C3292627/layers/25EAD662-3F77-4EF6-BA49-4152CAB7F75A
