### ISSUE TITLE
Homepage links

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#202]
Markup only since styling is already in place for the various elements.

<img width="994" alt="screen shot 2018-04-04 at 15 31 33" src="https://user-images.githubusercontent.com/1991226/38314041-4fe7620e-381d-11e8-8404-ddccb1dd4405.png">

**Comment by Android63** [comment]
@Pro-Paul what if a link title wraps over two or more lines?

![screen shot 2018-04-10 at 11 37 53](https://user-images.githubusercontent.com/1991226/38552355-cbd478c6-3cb3-11e8-9314-51e4d1d8ff8c.png)

**Comment by penpadstudio** [comment]
As this is the homepage we can have artist licence. You can even have LLA's as the heading and explain the LLA in the descriptive text below.

**Comment by Android63** [comment]
OK but what if a link title wraps over two or more lines?

**Comment by penpadstudio** [comment]
The line height will address this spacing issue.
