### ISSUE TITLE
Add Social Media Icons to footer

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#215]
Add the social media icons to the footer:
<img width="502" alt="screen shot 2018-04-11 at 10 06 43" src="https://user-images.githubusercontent.com/23170050/38607265-0e5b95fa-3d70-11e8-9ad3-fc6a20b6e02f.png">

**Comment by cehwitham** [comment]
Hi Paul, please can you provide the image files for the icons?

**Comment by penpadstudio** [comment]
Logos are already built on sprites on repo, just need placement in footer:

![screen shot 2018-04-11 at 15 52 08](https://user-images.githubusercontent.com/23170050/38624599-5d8d3b30-3da0-11e8-9192-d001e5c56f62.png)
