### ISSUE TITLE
Build Search results snippet

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#220]
so it look something like this using elements already built:
<img width="672" alt="screen shot 2018-04-11 at 10 22 52" src="https://user-images.githubusercontent.com/23170050/38608097-5bd002ce-3d72-11e8-9e8a-d0d6e0455d8b.png">

**Comment by cehwitham** [comment]
@Pro-Paul can we build this out of existing elements or does it specifically need to be its own component? Looks fairly similar to the post listing component we've already used?

**Comment by penpadstudio** [comment]
@cehwitham use existing elements, it does not need to be its own component unless we build one.

**Comment by cehwitham** [comment]
@Android63 does this have an impact on the LDP Hub search results?

**Comment by Android63** [comment]
I just need to change the "read more" link @cehwitham. This is how it looks in LDP Hub at the moment:
<img width="1022" alt="screen shot 2018-04-16 at 13 00 41" src="https://user-images.githubusercontent.com/1991226/38807975-5e47c390-4176-11e8-8a05-ec080f53ede9.png">

**Comment by cehwitham** [comment]
Also needs the horizontal divider and the search result count adding @Android63

**Comment by Android63** [comment]
Oh yes, thanks @cehwitham. I've added it as an issue at https://github.com/NHSLeadership/nightingale-wp/issues/116
