### ISSUE TITLE
Including .css files with @import is non-standard behaviour

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#228]
DEPRECATION WARNING on line 85, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

**Comment by Android63** [comment]
@csswizardry what do you think about this?

**Comment by penpadstudio** [comment]
@Android63 is this resolved?
