### ISSUE TITLE
Listing pages on mobile

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#248]
The layout of article listing pages on mobile needs improving.

![screen shot 2018-06-18 at 16 47 08](https://user-images.githubusercontent.com/1991226/41547161-58c9710c-7317-11e8-99d9-4eeb5bac1161.png)

Although articles are separated by horizontal rules, they are quite close together and people with dyslexia might struggle to tell where one ends and another begins.

Also, left and right aligned dates, read more, author etc. should sit on the same line instead of taking up the full width and pushing other items further down into the next article.

Finally, use semantic tags for articles, asides etc.

**Comment by penpadstudio** [comment]
@Android63 we will test this in testing after launching corp site please feel free to raise after.
