### ISSUE TITLE
Beta ribbon

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#251]
#### Summary:
The open in new window/tab icon is incorrect on the beta ribbon. 

#### Steps to reproduce:
Open any page on the staging site. https://nhslwpcorporate.nightingale.qa.kops.nhsx.uk/

#### Expected results:
The open in new window/tab icon should be NHS black.
<img width="665" alt="screen shot 2018-07-11 at 15 22 17" src="https://user-images.githubusercontent.com/23170050/42578382-47353796-851e-11e8-8454-e45ae109eaa3.png">

#### Actual results:
The open in new window/tab icon is currently NHS White.
![screen shot 2018-07-11 at 15 21 08](https://user-images.githubusercontent.com/23170050/42578253-16d25ee4-851e-11e8-8b9d-0a1924848c5f.png)

**Comment by penpadstudio** [comment]
Nightingale wiki for reference: https://github.com/NHSLeadership/nightingale/wiki/%28c%29Prototype-Ribbons

**Comment by csswizardry** [comment]
This is correct in Nightingale itself (i.e. this repo) so if there’s a bug elsewhere it probably needs filing elsewhere. This is what current `develop` looks like:

![image](https://user-images.githubusercontent.com/751944/44086309-0b7793b0-9fb4-11e8-8d01-2b7ef5c5a9e6.png)

**Comment by cehwitham** [comment]
@Android63 @ishanivardhan are you able to implement this with the black icon in Moodle and WP?

**Comment by csswizardry** [comment]
FYI, the bug is in the implementation, not Nightingale. We just need to remove the `u-links-darkbg` class 👍

![image](https://user-images.githubusercontent.com/751944/44088651-e175db46-9fbb-11e8-9ac9-8f8a627c3957.png)
