### ISSUE TITLE
Beta headline 

### ISSUE THREAD

**Issue by Pro-Paul** [NHSLeadership/nightingale#50]
Beta headline bar, the copy should be constrained by the one column grid width.

**Comment by csswizardry** [comment]
Whilst this is absolutely doable, I’m concerned about building in so much inflexibility—what if someone translates the page into a different language, or increases their font size, of we ever need to use words longer than _Beta_.

I’d recommend letting the size of the lozenge be dictated by its content, that way we never need to intervene—flexible by default.

(We can increase left/right padding to let it breathe though—that’s totally fine.)

Thoughts? :)

**Comment by csswizardry** [comment]
TODO: Constrain overall width to fit inside of page wrapper, rather than being automatically full width.

**Comment by penpadstudio** [comment]
@csswizardry also need to update copy content as in sketch file:
https://github.com/NHSLeadership/Sketch-Leadership-Academy-FEF-Template-Kit

**Comment by penpadstudio** [comment]
@csswizardry also update Alpha & Beta to bold.

**Comment by penpadstudio** [comment]
@csswizardry update close cross button on right to 
![screen shot 2017-06-09 at 10 11 44](https://user-images.githubusercontent.com/23170050/26968996-0edf3456-4cfc-11e7-9b38-da7d35e92f77.png)

as in sketch file.
