### ISSUE TITLE
Fonts being served from assets is a problem.

### ISSUE THREAD

**Issue by chriscoffee** [NHSLeadership/nightingale#52]
@jdbrew has been working on putting together a prototype kit to scaffold parts of the site quickly and prototype stuff fast similar to the gov site.

However, due to fonts being hard coded to assets/fonts it's proving difficult to get them served correct. Given you can't extend @font-face and I've tried serving the fonts from /assets/fonts in the router it's still not having it.

For the time being I'll just switch out the hardcoded route here until we have chat about it.

**Comment by csswizardry** [comment]
Heyyo!

I’m not sure I fully understand the issue I’m afraid. As in, what was it about `assets/fonts` that was proving <q>difficult to get them served correct</q>?

The difference between `assets/fonts` and `fonts` is minimal, so there’s nothing about this change I dislike—I’d just like to understand the problem a little more is all 😊

**Comment by csswizardry** [comment]
Closing in response to https://github.com/NHSLeadership/nightingale/commit/989ca456551e2b8fe0c2c5ca5683e1bcfb0d13ec#commitcomment-22341828

**Comment by chriscoffee** [comment]
For the reference of other developers. This fixed this issue: https://github.com/NHSLeadership/nightingale/commit/bb201dca22536c882cd000d2d312f50ea240201f
