### ISSUE TITLE
Wrapping element fixes

### ISSUE THREAD

**Issue by csswizardry** [NHSLeadership/nightingale#62]
The `.o-wrapper` element has overly large gutters on mobile and doesn’t contain floats properly.

**Comment by ishanivardhan** [comment]
@csswizardry - Wrt your Responsive wrapper paddings, npm run build throws below error when integrated in Moodle.

Error: "message": "no mixin named mq
Backtrace:node_modules/nightingale/objects/_objects.wrappers.scss:17"

Can you please check? Thanks!

**Comment by csswizardry** [comment]
Have you run `npm install` to grab the Sass-MQ (etc.) dependencies?

**Comment by ishanivardhan** [comment]
Yes, but to no luck. Just ran ```npm install``` followed by ```npm update``` again but still the same error. I had to comment this piece of code as it wasn't allowing me to build for the moment.

**Comment by csswizardry** [comment]
Hmm. I just took a fresh clone, ran `npm install` and `npm run watch` (there isn’t a `build` task) back to back and everything worked just fine.

Have you included [Sass MQ](https://github.com/sass-mq/sass-mq)?

```scss
@import "path/to/sass-mq/mq";
```

That’s the dependency that the `mq` mixin comes from.

**Comment by ishanivardhan** [comment]
There you go! Yes that's what was missing. Imported it, works fine now. 
Since I'm working on Moodle theme, I'm importing SASS files bit by bit as I need them instead of importing entire main.scss at once (atleast for now) and probably missed importing sass-mq separately. Thanks!
