### ISSUE TITLE
Header & Footer purple banner height

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#67]
swap from 15px to 10px

**Comment by csswizardry** [comment]
@p5uln:

<img width="1440" alt="screen shot 2017-06-08 at 10 52 01" src="https://user-images.githubusercontent.com/751944/26922944-976ef758-4c38-11e7-9bb7-297278431249.png">

**Comment by penpadstudio** [comment]
@csswizardry can we check that the footer also uses same 10px height on purple banner.
