### ISSUE TITLE
Update to links in Typography Styling

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#70]
@csswizardry Updates to links:
<img width="179" alt="screen shot 2017-06-09 at 11 58 12" src="https://user-images.githubusercontent.com/23170050/26972741-eeccdc40-4d0a-11e7-8b7d-4673c7116c79.png">

See latest sketch commit: https://github.com/NHSLeadership/Sketch-Leadership-Academy-FEF-Template-Kit

**Comment by csswizardry** [comment]
Note to self: let’s implement:

```css
a {
  text-decoration-skip: ink;
}
```
