### ISSUE TITLE
Form Styles

### ISSUE THREAD

**Issue by csswizardry** [NHSLeadership/nightingale#77]
This is a pretty monolithic issue right now, so we might need to break it down as we progress.

**Comment by csswizardry** [comment]
@p5uln 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3R202h1x0o0A1H3l262X/Screen%20Recording%202017-06-10%20at%2011.48%20am.gif?X-CloudApp-Visitor-Id=138442&v=e6718d9d)

**Comment by penpadstudio** [comment]
@csswizardry Above screencast looks good aside from bullet points.

**Comment by csswizardry** [comment]
![image](https://user-images.githubusercontent.com/751944/27729186-bbc0f62e-5d7c-11e7-8d17-92ba4ea64903.png)

We’ll have to drop these (×) clear-content icons—stuff like this should be handled by the operating system instead of us attempting to replicate it.

**Comment by csswizardry** [comment]
![image](https://user-images.githubusercontent.com/751944/27729268-1a0144fa-5d7d-11e7-83e8-ec3725cb321b.png)

~~Despite looking super-simple, the italicised text isn’t going to be possible without JS. There’s no way in CSS to tell whether a form field has any content in it, so we can’t un-italicise any forms that have been filled out.~~

This is actually super-simple—I forgot about `::placeholder` 😣

**Comment by csswizardry** [comment]
![image](https://user-images.githubusercontent.com/751944/27729678-983e3e8a-5d7e-11e7-86a5-f0bbe8e593c7.png)

I’d be **very** keen to keep these dropdowns as native browser UI so that we get better experience on mobile, as per:

![nightingale](https://user-images.githubusercontent.com/751944/27729934-88bb35f2-5d7f-11e7-90b9-adc146be61ad.png)

If we try to make our own implementation, we’ll just leave users dealing with an unfamilar UI.
