### ISSUE TITLE
Asset mapping introduction

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#78]
We need to setup an example mapping file (middleware) to enable @Android63 and @ishanivardhan  to start mapping some styles on to WordPress and Moodle while Nightingale is in development so that we can spot any issues early.

Form elements in WordPress are likely to be an area where this needs to be used as Gravity Forms has very specific markup that isn't easily changed.

**Comment by Android63** [comment]
I have this working and happy to explain/help as necessary.
