### ISSUE TITLE
Get WP theme consuming Sass

### ISSUE THREAD

**Issue by csswizardry** [NHSLeadership/nightingale#81]
Currently the WP theme consumes the monolithic, compiled CSS files, whereas it would be nice to have it consuming the Sass so that we can begin passing in our own config (e.g. writing out new asset URLs).

**Comment by cehwitham** [comment]
@Android63 and I have worked on this and think we have a working solution. @Android63 is going to test some of the mapping once he's updated the watch command but we should be in business.

**Comment by Android63** [comment]
I believe this is working fine now. I'm using npm to build css as needed.
