### ISSUE TITLE
Header button with icon

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#87]
![screen shot 2017-07-12 at 17 18 27](https://user-images.githubusercontent.com/2518941/28127992-23ea1426-6726-11e7-8579-7857f85dac7d.png)

**Comment by penpadstudio** [comment]
@cehwitham This is an old design version of login button, we will not be putting an icon on the button any longer for v.1 release.

**Comment by penpadstudio** [comment]
![screen shot 2017-09-08 at 10 19 19](https://user-images.githubusercontent.com/23170050/30204952-310056bc-947f-11e7-8a76-39f2e0b63438.png)

**Comment by penpadstudio** [comment]
@cehwitham I believe this issue can be closed, do you agree. From what I can try to understand it was opened about the icon being on the login, which is no longer the case, correct?
