### ISSUE TITLE
Data items, stat with explainer, progress bar

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#89]
![screen shot 2017-07-12 at 17 16 56](https://user-images.githubusercontent.com/2518941/28127905-ed4e329e-6725-11e7-9d7a-1a40beba87ba.png)

**Comment by penpadstudio** [comment]
Image above looks like font is not bold like below
<img width="676" alt="screen shot 2017-09-08 at 11 17 24" src="https://user-images.githubusercontent.com/23170050/30207393-4dbbb46a-9487-11e7-96a4-d9c1bf11f960.png">

**Comment by penpadstudio** [comment]
Unless I am mistaken I don't this the data set 1 has been built into Nightingale. 
The progress bar is there though but as an old design:
![screen shot 2018-07-09 at 14 12 14](https://user-images.githubusercontent.com/23170050/42452514-22f9bdc2-8382-11e8-9a7e-e645bb55f8a2.png)

**Comment by cehwitham** [comment]
@Pro-Paul it sounds like this is a pretty old issue.

Should we close this and split it into the 3 component parts of the new design? Could you create issues please? Are these in v1.0?
