### ISSUE TITLE
Comment forms

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#95]

**Comment by cehwitham** [comment]
![screen shot 2017-07-12 at 17 13 14](https://user-images.githubusercontent.com/2518941/28127720-6b03c93e-6725-11e7-92af-4a941a81f6b9.png)

**Comment by cehwitham** [comment]
@csswizardry did #96 cover this completely or is there further work required?

**Comment by csswizardry** [comment]
@cehwitham: This is done; anything new would be a bug or a change.
