### ISSUE TITLE
Story panel

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#97]
![screen shot 2017-07-12 at 17 06 51](https://user-images.githubusercontent.com/2518941/28127557-e16c9818-6724-11e7-9236-6929bd9d66e0.png)

**Comment by penpadstudio** [comment]
I believe this can be closed as the article (excerpts) are now built into Nightingale:

![screen shot 2018-07-09 at 14 15 36](https://user-images.githubusercontent.com/23170050/42452670-a230557e-8382-11e8-8eb1-2955659146ab.png)
