### ISSUE TITLE
Font license issues

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#98]
I'm going to hazard a guess that we don't have a license to distribute the Frutiger font? @jdbrew can probably confirm.

Therefore, given we've open sourced this repo, can we come up with a way to remove the font files and include them in an install/build from a private repo please @csswizardry?

@ishanivardhan @Android63 this will possibly have knock on effects for the WP and Moodle themes too.

**Comment by csswizardry** [comment]
Had a quick chat with @chriscoffee about this. We were under the impression that the fonts were being authed because

1. the filenames appear to reflect an auth token;
2. @chriscoffee had to whitelist some domains.

On further reflection, though, we realised that this couldn’t possibly be functional/implemented because we’re not actually hitting a provider’s service to do any authentication.

I’d rather self-host for performance and resilience reasons, but using a managed solution will solve the authentication/licensing issues.

One to discuss.

**Comment by Android63** [comment]
I'm sure @Pro-Paul won't like this suggestion, but what about using an open-source font that's close enough to do the trick?

**Comment by cehwitham** [comment]
It's against brand guidelines @Android63. If we have to use a fallback, I think it has to be Arial.

**Comment by Android63** [comment]
It's against brand guidelines to use an open-source font? Perhaps we should challenge the brand guidelines then!

> One of the issues with Frutiger is that it's not a font that was designed for the web (it was designed in 1968...). And it is a licensed font. I don't know which license you have, but you assured us in #70 it was ok. Either way, if you are worried about a licensed font being easily downloaded, just use an open sourced one, then no-one will get concerned and you respect their license.
> 
> We understand the desire to use a swiss designed font (commissioned for an airport in Paris), but this isn't a font that should be used on a website. We suggest the solution of switching to an open-source webfont:
> 
> It won't cost you anything
> It doesn't need to be protected
> It's designed for the web, so no readability/rendering issue
> It's widely supported (surely already cached on the user's computer for a Google Font)
> You don't have to host it yourselves

Source: https://github.com/swiss/styleguide/issues/317

If found this one that's fairly close to Frutiger: https://fonts.google.com/specimen/Istok+Web

**Comment by csswizardry** [comment]
> One of the issues with Frutiger is that it's not a font that was designed for the web…

It will have been re-hinted for the web, though. I feel like that’s a weak (it not moot) argument they’re making.

Surely there’s official word somewhere in the NHS about how we tackle this problem? We can’t be the first to have encountered it. Licensing Frutiger afresh for the kinds of traffic the NHS gets will cost _thousands_ a month!

**Comment by cehwitham** [comment]
Had a chat with @jdbrew and the official brand guidelines state Arial as the fallback. Therefore, could we remove all the font files from this repo and set Nightingale up to use Arial as default for the open source resource. We'll then need a way to bring the Frutiger font into our downstream projects where we can control the licensing. We probably need to keep it out of the WordPress and Moodle theme repos too though. Presumably we could specify Frutiger in the font stack though and it would display if installed locally or we can web host it for our own products.
