### ISSUE TITLE
Screen reader class needed

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#99]
Class with name something like `screen-reader-text` is needed to hide text that is only for screen readers (such as "Skip to content" links)

**Comment by csswizardry** [comment]
On its way in soon: f2b48cbdc5396022f43a8437a0b21c347a457e21 👍

**Comment by csswizardry** [comment]
@Android63: This is now available in the latest release 👍

**Comment by Android63** [comment]
Thanks @csswizardry
